name: My First Github Action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
      - run: echo "hello world!!!!!!"
      - run : echo "this is step number 3"