# name: My First Github Action
# on: [push]
# jobs:
#   print-hello-world:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "hello world!!!!!!"
#       - run : echo "this is step number 3"

name: My First Github Action
on: [push]
jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build-the-project  # Fixed indentation and removed spaces around colon
        run: yarn build           # Fixed indentation
      - name: Setup Build        # Fixed indentation
        run: echo "Hurray"       # Fixed indentation

        
     # - run : tree # is used to perform the execution